### ISSUE TITLE
No licence specified

### ISSUE THREAD

**Issue by SteveALee** [gleborgne/winjscontrib#2]
There is no LICENSE.txt file and I could find nothing from searching a few files. There are so many reason to defined your licensing terms eg

http://archive.alt.ac.uk/alt.newsweaver.co.uk/www.oss-watch.ac.uk/resources/opensourceyourcode.html
from github:
http://choosealicense.com/
http://choosealicense.com/about/

**Comment by lahloumehdi** [comment]
Hello,

We have added a new section (and file).

Thank you !

**Comment by SteveALee** [comment]
I guess you need to push as I can't see it yet?

**Comment by lahloumehdi** [comment]
https://github.com/gleborgne/winjscontrib#license :)

**Comment by SteveALee** [comment]
Nice choice!
